@startuml

actor "Front of House" as FoH
actor Guest
actor "Floor Manager" as FM
actor Administrator
actor Employee

!include "generic/overview.puml"
!include "hotel/overview.puml"
!include "restaurant/overview.puml"
!include "events/overview.puml"

@enduml
