@startuml

left to right direction

actor Administrator
actor "General Manager" as GM
actor "Security" as sec

rectangle "User Administration System" {
    (Register employee) as (reg)
    (View  all employees) as (view)
    (Delete employee) as (del)
    (Assign roles to employee) as (ass)

    Administrator --> (reg)
    Administrator --> (view)
    Administrator --> (del)
    Administrator --> (ass)

    (reg) <-- GM
    (view) <-- GM
    (del) <-- GM
    (ass) <-- GM


    (view) <-- sec
}

@enduml
