@startuml

left to right direction

actor Guest
actor Employee
actor Manager

rectangle "Authentication System" {
    (Logon to the system) as (Login)
    (Logoff from the system) as (Logout)

    Guest --> (Register)
    Guest --> (Login)
    Guest --> (Logout)

    (Login) <-- Employee
    (Logout) <-- Employee

    (Login) <-- Manager
    (Logout) <-- Manager
}

@enduml
