@startuml

left to right direction

actor Guest
actor Employee
actor Administrator
actor "General Manager" as GM

rectangle "Authentication System" {
    (Logon to the system) as (Login)
    (Logoff from the system) as (Logout)

    Guest --> (Register)
    Guest --> (Login)
    Guest --> (Logout)

    (Login) <-- Employee
    (Logout) <-- Employee

    (Login) <-- Administrator
    (Logout) <-- Administrator

    GM --> (Login)
    GM --> (Logout)
}

@enduml
