@startuml

left to right direction

actor "Front of House" as FoH
actor Waiter

rectangle "Beverage Management System v0.3" {
    (View menu) as (MenuView)
    (Modify menu) as (MenuUpdate)

    (View menu item) as (MenuItemView)
    (Modify menu item) as (MenuItemUpdate)

    (View all beverages) as (BeverageAll)
    (Modify beverage order list) as (BeverageUpdate)
    (Order beverages) as (BeverageOrder)
    (View orders) as (BarOrderView)
    (litre) as (BeverageQuantity)
    (BeverageOrder) .> (BeverageQuantity) : optional

    FoH --> (MenuView)
    FoH --> (MenuUpdate)
    FoH --> (MenuItemView)
    FoH --> (MenuItemUpdate)

    FoH --> (BeverageAll)
    FoH --> (BeverageUpdate)
    FoH --> (BeverageOrder)
    FoH --> (BarOrderView)

    (MenuView) <-- Waiter
    (MenuItemView) <-- Waiter
    (BeverageAll) <-- Waiter
    (BarOrderView) <-- Waiter
}

@enduml
