@startuml

left to right direction

actor "Front of House" as FoH
actor Guest
actor Waiter

rectangle "Restaurant Billing System v 0.2" {
    (View restaurant bill) as (TableBillView)
    (Pay restaurant bill) as (TableBillPay)
    (Print restaurant bill) as (TableBillPrint)
    (Add bill to existing hotel invoice) as (TableBillAdd)

    Guest --> (TableBillView)
    Guest --> (TableBillPay)
    Guest --> (TableBillAdd)

    (TableBillView) <-- FoH
    (TableBillPrint) <-- FoH

    (TableBillView) <-- Waiter
    (TableBillPrint) <-- Waiter
}

@enduml
