@startuml

left to right direction

actor "Front of House" as FoH
actor "Walk-in guest" as WG
actor "Hotel guest" as HG
actor Waiter

rectangle "Billing System v0.3" {
    (View restaurant bill) as (TableBillView)
    (Pay restaurant bill) as (TableBillPay)
    (Print restaurant bill) as (TableBillPrint)
    (Add bill to existing hotel invoice) as (TableBillAdd)

    WG --> (TableBillView)
    WG --> (TableBillPay)

    HG --> (TableBillView)
    HG --> (TableBillPay)
    HG --> (TableBillAdd)

    (TableBillView) <-- FoH
    (TableBillPrint) <-- FoH

    (TableBillView) <-- Waiter
    (TableBillPrint) <-- Waiter
}

@enduml
