@startuml

left to right direction

actor "Front of House" as FoH
actor Guest
actor Waiter

rectangle "Restaurant Billing System" {
    (View restaurant bill) as (TableBillView)
    (Pay restaurant bill) as (TableBillPay)
    (Print restaurant bill) as (TableBillPrint)

    Guest --> (TableBillView)
    Guest --> (TableBillPay)

    (TableBillView) <-- FoH
    (TableBillPrint) <-- FoH

    (TableBillView) <-- Waiter
    (TableBillPrint) <-- Waiter
}

@enduml
