@startuml

left to right direction

actor "FoH and Chef" as FC
actor "Kitchen Staff" as KS

rectangle "Kitchen Management System v0.3" {
    (View menu) as (MenuView)
    (Modify menu) as (MenuUpdate)
    

    (View menu item) as (MenuItemView)
    (Modify menu item) as (MenuItemUpdate)

    (View all ingredients) as (IngredientAll)
    (Modify ingredient order list) as (IngredientUpdate)
    (Order ingredients) as (IngredientOrder)
    (View orders) as (KitchenOrderView)
    (KG, Gram, pieces) as (IngredientQuantity)

    (IngredientOrder) .> (IngredientQuantity) : optional

    FC --> (MenuView)
    FC --> (MenuUpdate)
    FC --> (MenuItemView)
    FC --> (MenuItemUpdate)
    FC --> (IngredientAll)
    FC --> (IngredientUpdate)
    FC --> (IngredientOrder)
    FC --> (KitchenOrderView)

    (MenuView) <-- KS
    (MenuItemView) <-- KS
    (IngredientAll) <-- KS
    (KitchenOrderView) <-- KS
}

@enduml
