@startuml

left to right direction

actor Chef
actor "Kitchen Staff" as KS

rectangle "Kitchen Management System v 0.2" {
    (View menu) as (MenuView)
    (Modify menu) as (MenuUpdate)

    (View menu item) as (MenuItemView)
    (Modify menu item) as (MenuItemUpdate)

    (View all ingredients) as (IngredientAll)
    (Modify ingredient) as (IngredientUpdate)
    (Order ingredients) as (IngredientOrder)
    (View orders) as (KitchenOrderView)
    (KG, Gram, pieces) as (IngredientQuantity)

    (IngredientOrder) .> (IngredientQuantity) : optional

    Chef --> (MenuView)
    Chef --> (MenuUpdate)
    Chef --> (MenuItemView)
    Chef --> (MenuItemUpdate)

    Chef --> (IngredientAll)
    Chef --> (IngredientUpdate)
    Chef --> (IngredientOrder)
    Chef --> (KitchenOrderView)

    (MenuView) <-- KS
    (MenuItemView) <-- KS
    (IngredientAll) <-- KS
}

@enduml
