@startuml

left to right direction

actor "Hotel/Walk-in guest" as Guest

rectangle "Order from menu v0.3" {
    Guest --> (View menu)
    Guest --> (Order food from menu)
    Guest --> (Order drink from menu)
}

@enduml