@startuml
rectangle "Restaurant v0.3" #eeeeff {
    !include "reservation.puml"
    !include "menu.puml"
    !include "billing.puml"
    !include "kitchen.puml"
    !include "bar.puml"
    !include "supplier.puml"
}
@enduml
