@startuml

left to right direction

actor "Front of House" as FoH
actor Waiter
actor Guest

rectangle "Restaurant Reservation System v 0.2" {
    (View available dates) as (TableAll)
    (Book table reservation for guest) as (TableBook)
    (Select 3-, 5-, 7-course menu) as (TableCourse)
    (Cancel table reservation of guest) as (TableCancel)

    Guest --> (TableAll)
    Guest --> (TableBook)
'    Guest ..> (TableCourse) : optional
    (TableBook) .> (TableCourse) : optional
    Guest --> (TableCancel)

    (TableBook) <-- Waiter
    (TableCancel) <-- Waiter

    (TableBook) <-- FoH
    (TableCancel) <-- FoH

}

@enduml
