@startuml

left to right direction

actor "Front of House" as FoH
actor Chef

rectangle "Bar Supply Management System" {
    (View all suppliers) as (BarSupplyAll)
    (View supplier) as (BarSupplyView)
    (Add supplier) as (BarSupplyAdd)
    (Modify supplier) as (BarSupplyUpdate)

    FoH --> (BarSupplyAll)
    FoH --> (BarSupplyView)
    FoH --> (BarSupplyAdd)
    FoH --> (BarSupplyUpdate)
}

rectangle "Restaurant Supply Management System" {
    (View all suppliers) as (RestaurantSupplyAll)
    (View supplier) as (RestaurantSupplyView)
    (Add supplier) as (RestaurantSupplyAdd)
    (Modify supplier) as (RestaurantSupplyUpdate)

    Chef --> (RestaurantSupplyAll)
    Chef --> (RestaurantSupplyView)
    Chef --> (RestaurantSupplyAdd)
    Chef --> (RestaurantSupplyUpdate)
}

@enduml
