@startuml

left to right direction

actor "Front of House" as FoH
actor "FoH and Chef" as FC

rectangle "Food Supply Management System v0.3" {
    (View all suppliers) as (RestaurantSupplyAll)
    (View supplier) as (RestaurantSupplyView)
    (Add supplier) as (RestaurantSupplyAdd)
    (Modify supplier) as (RestaurantSupplyUpdate)

    FC --> (RestaurantSupplyAll)
    FC --> (RestaurantSupplyView)
    FC --> (RestaurantSupplyAdd)
    FC --> (RestaurantSupplyUpdate)
}

rectangle "Beverage Supply Management System v0.3" {
    (View all suppliers) as (BarSupplyAll)
    (View supplier) as (BarSupplyView)
    (Add supplier) as (BarSupplyAdd)
    (Modify supplier) as (BarSupplyUpdate)

    FoH --> (BarSupplyAll)
    FoH --> (BarSupplyView)
    FoH --> (BarSupplyAdd)
    FoH --> (BarSupplyUpdate)
}

@enduml
