@startuml

left to right direction

actor General.Manager
actor Security.Guard


rectangle "Hotel Reservation System" {
    (Book room reservation for guest) as (RoomBook)
    (Cancel room reservation of guest) as (RoomCancel)
    (Make a booking definitive) as (BookingDefinite)
    (See availability of a room) as (RoomAvailable)
    (See room occupancy) as (RoomOccupancy)
    (See room information) as (RoomInfo)
    (View invoice) as (RoomInvoice)
    (Print invoice) as (PrintInvoice)
    (View Guest information) as (GuestInfo)
    (Check-in) as (Checkin)
    (Check-out) as (Checkout)
    (Set Room availability) as (SetRoomAvailable)
    (Set status clean) as (StatusClean)
    (Set status to clean) as (StatusToclean)
    (Enlist guest for newsletter) as (NewsLetter)

    (RoomBook) <-- General.Manager
    (RoomCancel) <-- General.Manager
    (BookingDefinite) <-- General.Manager
    (RoomAvailable) <-- General.Manager
    (RoomOccupancy) <-- General.Manager
    (RoomInfo) <-- General.Manager
    (RoomInvoice) <-- General.Manager
    (PrintInvoice) <-- General.Manager
    (StatusClean) <-- General.Manager
    (StatusToclean) <-- General.Manager
    (GuestInfo) <-- General.Manager
    (Checkin) <-- General.Manager
    (Checkout) <-- General.Manager
    (SetRoomAvailable) <-- General.Manager
    (NewsLetter) <-- General.Manager

     Security.Guard --> (RoomAvailable)
     Security.Guard --> (RoomOccupancy)
     Security.Guard --> (RoomInfo)
     Security.Guard --> (RoomInvoice)
     Security.Guard --> (PrintInvoice)
     Security.Guard --> (GuestInfo)
     Security.Guard --> (Checkin)
     Security.Guard --> (Checkout)


}

@enduml