@startuml

left to right direction

actor Receptionist
actor Guest

rectangle "Room Service System" {
    (View room service menu) as (RSMenu)
    (Order food from menu) as (RSFood)
    (Order drink from menu) as (RSDrink)

    (RSMenu) <-- Receptionist
    (RSFood) <-- Receptionist
    (RSDrink) <-- Receptionist

    Guest --> (RSMenu)
    Guest --> (RSFood)
    Guest --> (RSDrink)
}

@enduml
